apiVersion: v1
kind: Service
metadata:
  name: new-frontend
spec:
  type: NodePort
  selector:
    app: new-frontend
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 5173