apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-fullstack-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-fullstack
  template:
    metadata:
      labels:
        app: todo-app-fullstack
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3d-k3s-default-agent-0
      volumes:
        - name: shared-images
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: frontend
          image: junior246/new_frontend
          ports: 
           - containerPort: 5173
          volumeMounts:
          - name: shared-images
            mountPath: /usr/local/app/public/images
        - name: todo-app
          image: junior246/todo_app
          ports: 
           - containerPort: 8080
          volumeMounts:
          - name: shared-images
            mountPath: /sharedImages