apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-fullstack-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-fullstack
  template:
    metadata:
      labels:
        app: todo-app-fullstack
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3d-k3s-default-agent-0
      volumes:
        - name: shared-images
          persistentVolumeClaim:
            claimName: image-claim
        - name: config-properties
          configMap:
            name: todo-app-fullstack-config
            items:
              - key: application.properties
                path: application.properties
      containers:
        - name: frontend
          image: junior246/new_frontend
          ports: 
           - containerPort: 5173
          env:
          - name: VITE_FETCH_INTERVAL
            valueFrom:
              configMapKeyRef:
                name: todo-app-fullstack-config
                key: image-refresh-timer
          volumeMounts:
          - name: shared-images
            mountPath: /usr/local/app/public/images
        - name: todo-app
          image: junior246/todo_app
          ports: 
           - containerPort: 8080
          env:
            - name: IMAGE_SOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-fullstack-config
                  key: image-source-url
            - name: IMAGE_SHARED_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-fullstack-config
                  key: image-shared-path
          volumeMounts:
          - name: shared-images
            mountPath: /sharedImages
          - name: config-properties
            mountPath: /config
            readOnly: true