apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: project
  name: todo-app-fullstack-ingress
spec:
  rules:
  - http:
      paths:
      - path: /image
        pathType: Prefix
        backend:
          service:
            name: todo-app-fullstack-svc
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-app-fullstack-svc
            port:
              number: 5173
      - path: /images
        pathType: Prefix
        backend:
          service:
            name: todo-app-fullstack-svc
            port:
              number: 5173
      - path: /todos
        pathType: Prefix
        backend:
          service:
            name: todo-app-fullstack-svc
            port:
              number: 8080