apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
images:
  - name: TODO_IMAGE
    newName: europe-west3-docker.pkg.dev/project-8e8aec54-2e81-49e9-951/todo-repository/todo-app
    newTag: latest
  - name: TODO_FRONTEND_IMAGE
    newName: europe-west3-docker.pkg.dev/project-8e8aec54-2e81-49e9-951/todo-repository/frontend
    newTag: latest
resources:
  - secrets/secret.yaml
  - config.yaml
  - persistentvolumeclaim.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - cronjob.yaml
  - ingress.yaml

commonAnnotations:
  cloud.google.com/neg: '{"ingress": true}'