apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - secrets/secret.yaml
  - config.yaml
  - persistentvolumeclaim.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - cronjob.yaml
  - ingress.yaml

commonAnnotations:
  cloud.google.com/neg: '{"ingress": true}'