apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-gcs
  namespace: project
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-sa
          nodeSelector:
            iam.gke.io/gke-metadata-server-enabled: "true"
          containers:
          - name: backup-container
            image: postgres:18-alpine
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            command: ["/bin/sh", "-c"]
            args:
              - |
                set -e
                apk add --no-cache python3 py3-pip
                pip install gsutil --break-system-packages --no-cache-dir

                echo "[GoogleCompute]\nservice_account = default" > /tmp/.boto
                export BOTO_CONFIG=/tmp/.boto

                FILENAME="backup-$(date +%Y-%m-%d_%H-%M).sql"

                echo "Starting backup with native pg_dump..."
                pg_dump -h postgres-svc -U postgres -d todo > /tmp/$FILENAME

                echo "Uploading to GCS..."
                gsutil cp /tmp/$FILENAME gs://your-todo-backup-bucket/

                echo "Done!"
          restartPolicy: OnFailure