apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-gcs
  namespace: project
spec:
  schedule: "0 3 * * *" # TÃ¤glich um 03:00 Uhr
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-sa 
          containers:
          - name: backup-container
            image: google/cloud-sdk:alpine
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            command: ["/bin/sh", "-c"]
            args:
              - |
                set -e
                apk add --no-cache --repository=https://dl-cdn.alpinelinux.org postgresql18-client
                
                FILENAME="backup-$(date +%Y-%m-%d_%H-%M).sql"

                echo "Authenticating with Google Cloud..."
                gcloud auth activate-service-account --key-file=/secret/credentials.json

                echo "Starting database backup..."
                pg_dump -h postgres-svc -U postgres -d todo > /tmp/$FILENAME

                echo "Uploading $FILENAME to GCS..."
                gsutil cp /tmp/$FILENAME gs://your-todo-backup-bucket/

                echo "Backup successful: $FILENAME"
            volumeMounts:
            - name: gcs-key
              mountPath: /secret
              readOnly: true
          volumes:
          - name: gcs-key
            secret:
              secretName: gcs-backup-secret
          restartPolicy: OnFailure