apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-gcs
  namespace: project
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-sa
          nodeSelector:
            iam.gke.io/gke-metadata-server-enabled: "true"
          containers:
          - name: backup-container
            image: google/cloud-sdk:alpine
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            command: ["/bin/sh", "-c"]
            args:
              - |
                set -e
                apk add --no-cache --repository=http://dl-cdn.alpinelinux.org postgresql18-client
                
                FILENAME="backup-$(date +%Y-%m-%d_%H-%M).sql"
                pg_dump -h postgres-svc -U postgres -d todo > /tmp/$FILENAME
                
                gcloud storage cp /tmp/$FILENAME gs://your-todo-backup-bucket/

                echo "Done!"
          restartPolicy: OnFailure