apiVersion: v1
kind: Service
metadata:
  name: todo-app-fullstack-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app-fullstack
  ports:
    - name: todo-app
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: frontend
      port: 5173
      targetPort: 5173 