apiVersion: ENC[AES256_GCM,data:29g=,iv:zjMwYAFTIJ3eJHMmv56imWOvYLmkG02uPBkdMzHt2FU=,tag:kXoo4wUWGFqqwVoAK3IXvA==,type:str]
kind: ENC[AES256_GCM,data:Fd/VFNkM,iv:lltqtAl4KFnvMyecyIpcnqCrdwviRuFxy/NHmZ/sqec=,tag:XfsHEBV4HtnSOzh+t9979A==,type:str]
metadata:
    namespace: ENC[AES256_GCM,data:wfb57qUbwA==,iv:wYzeojtxDf+N3COoA3WrGJWYiJKzSHJi+yGs9uXvVl0=,tag:+4vcnSx67C/90KMvJqu9yQ==,type:str]
    name: ENC[AES256_GCM,data:+qdT2uNctVonQDUMhZMu,iv:7Oq3kFWEjMH2MIM0bWBYJy0LH7GVz6uF/g4OI8ZRJZE=,tag:t4FUdSF4c5iM33xvl14wBg==,type:str]
type: ENC[AES256_GCM,data:9oLdUVTi,iv:+aULMZZb7hUz08cwulniGnaDOEHaiNttRYgwxKT6TgE=,tag:EZiFFbtaWtMipXpZDeLKNQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:1feVR1xX23KX6YeIRooWvgBs/NvWM0SZq+YpTpxcEvUuXgpsWA57,iv:4HKckpXQkU3rDYwFmwxofq743YXCq7clG7lwUFmejTg=,tag:dXUdQBXxQgjs8QtMh0RIgg==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:FthlVrDI,iv:m5BUzT0ku7RCm+xtMqAhvZ2R7gFcbKjo7h4GcOtHDpA=,tag:jD5R9EbnUmRB756skl9K6w==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/project-8e8aec54-2e81-49e9-951/locations/global/keyRings/sops-keyring/cryptoKeys/sops-key
          created_at: "2026-01-30T11:27:07Z"
          enc: CiQA0dkOFx8L6gNE7V3antxnz/9A41QnDkzHsfa5fOyw3hr8onkSSQBQAPBDW7EnADy5r5ycEHkOm0pueBYH9B41GBLY9SQKPP9DrLa85N3Ctsytqosc9g6g/yoJCdhhKW5XmkQpDBb6ivF8/xhnQdg=
    lastmodified: "2026-01-30T11:27:07Z"
    mac: ENC[AES256_GCM,data:RZIiXwVVtQzX6bZ+RTVoD0ftWXNTc40C+0XO/5ZD7oRNMupOjFrgdaCiTaJeqRPjr/bolGkqd1/UotIGJUmimNGPae9TgMe/l3kDO0uwZ3XE+z6RVWY8Mbxm1aT/pby8WxQmfeBKHcbQh78mGqCe3WAO7EYpXB8Z+vX9JnLbCig=,iv:wGY55fdFKavtRvEzJTHwJPmORzY8vuniQodFs6dLhNk=,tag:eOo6OB8/ZHeNy+2POys17g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
