apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: postgres-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:M1/MVimoE0nVUiw+2z+yJBVckW1uRNuSwg/uZ/X489TLriRImr1Q,iv:F9TwjcAQzmAkHymh4ZJK6RDKhCjcO3QzUgYTrXjVwto=,tag:E57yCTzxs0tidFhI4+t1hQ==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QKErWuLJ,iv:JqShzpTKikryJnn2es0lMuNu3h3R3vPcSGmtD+ZGaoM=,tag:8uG/lVUlT4zrYeb3LWdm3g==,type:str]
sops:
    age:
        - recipient: age12kpl28gc6s8m2mn0erauva54y6rzlyqxyzjy5wwluvsgrec30caq0ee4n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydDlCS0Z5SGErVkFJdHJ6
            cVFUNkJac2hVNmxrOHdLNU1QSjl2dlBqOENzCmpJNzI1eEFBVUR1VndhcXU2Q0tQ
            MXdhVUdJeklWcGxCOWV3REpvTmN4emsKLS0tIHErYURkNTU3K1JUSXFXKzdqa2dS
            RG9uTkpnTFVUa1JwU1lIWVhhTE9hbEkK3zjOq2MyRgFc8TUKDbIfZJr4n1YMIHW3
            weSZD+e8qFhsbGcKXh5Qr8NKiMMQ7ruPSIvULPDVMl2nQvvqUeJtzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T10:09:08Z"
    mac: ENC[AES256_GCM,data:ZewleyVz+TepiSicAVZcla9nsjCypTbA9McA8OvlkDCtlg0fL3rZe3403UYkpPefTX5v6ZtUDxJTwQoeSMBIYHcxncwUsNQSBskglNpYNBVBtOhaze9r7a7Lv/3bGn9aqShIEIPs6uaDH4uFKuy9bjJtkPF/7UxRl27gIbseJd4=,iv:g3Sw/VtAGmDK1HI4R4gnpvZplbnoNHhlyaDJdLDuHSg=,tag:Mhtv5Hrzm0l3QfDVzsaEGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
