apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: random-string
          emptyDir: {}
      containers:
        - name: log-output-generate
          image: log_output_generate
          imagePullPolicy: Never
          volumeMounts:
          - name: random-string
            mountPath: /files
        - name: log-output-read
          image: log_output_read
          imagePullPolicy: Never
          volumeMounts: 
          - name: random-string
            mountPath: /files