apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-check
  namespace: exercises
spec:
  metrics:
  - name: cpu-usage-rate
    interval: 30s
    successCondition: result < 0.3
    failureLimit: 1
    provider:
      prometheus:
        address: http://kube-stack-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
        query: scalar(sum(rate(container_cpu_usage_seconds_total{namespace="exercises"}[5m])))