# Deployment Log-output
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      # volumes:
      #   - name: pong-counter
      #     persistentVolumeClaim:
      #       claimName: file-claim
      containers:
        - name: log-output
          image: junior246/log_output
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: message
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
          # volumeMounts:
          # - name: pong-counter
          #   mountPath: /files
      volumes:
        - name: config
          configMap:
            name: log-output-config
            items:
              - key: "information.txt"
                path: "information.txt"
---

# Deployment Ping-Pong
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      # volumes:
      #   - name: pong-counter
      #     persistentVolumeClaim:
      #       claimName: file-claim
      containers:
        - name: ping-pong-app
          image: junior246/ping_pong_app
          # volumeMounts:
          # - name: pong-counter
          #   mountPath: /files