# Deployment Log-output
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      # volumes:
      #   - name: pong-counter
      #     persistentVolumeClaim:
      #       claimName: file-claim
      containers:
        - name: log-output
          image: junior246/log_output
          # volumeMounts:
          # - name: pong-counter
          #   mountPath: /files
---

# Deployment Ping-Pong
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      # volumes:
      #   - name: pong-counter
      #     persistentVolumeClaim:
      #       claimName: file-claim
      containers:
        - name: ping-pong-app
          image: junior246/ping_pong_app
          # volumeMounts:
          # - name: pong-counter
          #   mountPath: /files