# Service Ping-Pong
apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-svc
spec:
  type: LoadBalancer
  selector:
    app: ping-pong
  ports:
    - port: 80
      targetPort: 8080

---
# Service Log-Output
apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: log-output-svc
spec:
  type: LoadBalancer
  selector:
    app: log-output
  ports:
    - port: 80
      targetPort: 8081