name: Release application

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster 
  GKE_ZONE: europe-west3-c
  REGISTRY: europe-west3-docker.pkg.dev
  REPOSITORY: todo-repository
  IMAGE_BACKEND: todo-app
  IMAGE_FRONTEND: frontend
  SERVICE: todo-app-fullstack-dep
  NAMESPACE: project

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/668823593060/locations/global/workloadIdentityPools/github/providers/github-provider'
          service_account: 'github-actions@project-8e8aec54-2e81-49e9-951.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Configure Docker
        run: gcloud --quiet auth configure-docker ${{ env.REGISTRY }}

      - name: Build and Publish Images
        run: |
          # Define paths
          REPO_BACKEND=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_BACKEND }}
          REPO_FRONTEND=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_FRONTEND }}
          
          # Backend: Build and Push with SHA and latest
          docker build -t $REPO_BACKEND:${{ github.sha }} -t $REPO_BACKEND:latest ./todo-app 
          docker push $REPO_BACKEND --all-tags
          
          # Frontend: Build and Push with SHA and latest
          docker build -t $REPO_FRONTEND:${{ github.sha }} -t $REPO_FRONTEND:latest ./frontend 
          docker push $REPO_FRONTEND --all-tags
          
          # FÃ¼r Kustomize SHA-Tag save
          echo "FINAL_TAG_BACKEND=$REPO_BACKEND:${{ github.sha }}" >> $GITHUB_ENV
          echo "FINAL_TAG_FRONTEND=$REPO_FRONTEND:${{ github.sha }}" >> $GITHUB_ENV

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Install sops
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          chmod +x sops-v3.8.1.linux.amd64
          sudo mv sops-v3.8.1.linux.amd64 /usr/local/bin/sops

      - name: Decrypt Kubernetes secret
        run: sops -d todo-app/manifests/secrets/secret.enc.yaml > todo-app/manifests/secrets/secret.yaml

      - name: Deploy
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [ "$BRANCH_NAME" = "main" ]; then
            DEPLOY_NAMESPACE="project"
          else
            DEPLOY_NAMESPACE=$BRANCH_NAME
          fi
          kubectl create namespace $DEPLOY_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
          cd todo-app/manifests
          kustomize edit set namespace $DEPLOY_NAMESPACE
          kustomize edit set image TODO_IMAGE=${{ env.FINAL_TAG_BACKEND }}
          kustomize edit set image TODO_FRONTEND_IMAGE=${{ env.FINAL_TAG_FRONTEND }}
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/${{ env.SERVICE }} -n ${{ env.NAMESPACE }} --timeout=120s